services:
  # Tracker 服务
  tracker:
    container_name: lunar-tracker
    restart: always
    build: .
    volumes:
      - tracker_files:/app/files
      - tracker:/app/openapi  # 挂载名为 tracker 的卷

  # NGINX 服务
  nginx:
    container_name: lunar-nginx
    image: nginx:alpine
    restart: always
    ports:
      - "40123:80"  # 将宿主机的 80 端口映射到容器的 10080 端口
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # 挂载自定义的 nginx 配置文件
      - tracker:/usr/share/nginx/openapi-html:ro  # 挂载 tracker 卷到 nginx 静态文件目录  
    depends_on:
      - tracker  # 确保 nginx 在 tracker 启动后再启动

volumes:
  tracker:
    driver: local  # 使用本地存储卷
  tracker_files:
    driver: local  # 使用本地存储卷
